esphomeyaml:
  name: livingroom_sensors
  platform: ESP8266
  board: nodemcuv2

sensor:
  - platform: adc
    pin: A0
    name: Living Room Temperature
    update_interval: 60s
    unit_of_measurement: "°C"
    accuracy_decimals: 1 
    icon: mdi:thermometer
    filters:
      - lambda: return (x/1024.0)*330000;
binary_sensor:
  - platform: gpio
    pin: D0
    name: Living Room Motion
    device_class: motion

wifi:
  ssid: 'salmona'
  password: !secret wifi_password
  manual_ip:
    static_ip: 192.168.86.104
    gateway: 192.168.86.1
    subnet: 255.255.255.0

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
